on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: edumserrano/github-issue-forms-parsern@v1
      #   with:
      #     who-to-greet: 'Mona the Octocat'
      # - run: echo random-number ${{ steps.foo.outputs.random-number }}
      #   shell: bash