name: Test GitHub action

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
    - "**.md"
  pull_request:
    branches: [ main ]
    paths-ignore:
    - "**.md"
  schedule:
    - cron: '0 0 * * 0' # Once a week: "At 00:00 on Sunday."

defaults:
  run:
    shell: pwsh

jobs:
  main:
    name: Test GitHub action
    environment: no-secrets-workflow
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get test input args
        id: input
        run: |
          $templateFilepath = './GitHubIssueFormsParser/tests/GitHubIssuesParserCli.Tests/TestFiles/Template.yml'
          $issueBody = Get-Content ./GitHubIssueFormsParser/tests/GitHubIssuesParserCli.Tests/TestFiles/IssueBody.md -Raw
          $issueBody = $issueBody -replace "\n","%0A" # The content must be escaped to preserve newlines. See https://github.community/t/set-output-truncates-multiline-strings/16852/3
          Write-Output "::set-output name=issue-body::$issueBody"
          Write-Output "::set-output name=template-filepath::$templateFilepath"
      - name: Dump outputs from previous step
        env:
          STEP_OUTPUT: ${{ toJSON(steps.input.outputs) }}
        run: $env:STEP_OUTPUT
      - name: Run GitHub issue form parser
        id: parser
        uses: edumserrano/github-issue-forms-parser@v1
        with:
          template-filepath: '${{ steps.input.outputs.template-filepath }}'
          issue-form-body: '${{ steps.input.outputs.issue-body }}'
      - name: Dump outputs from previous step
        env:
          STEP_OUTPUT: ${{ toJSON(steps.parser.outputs) }}
        run: $env:STEP_OUTPUT
      - name: Output and assert parsed issue
        run: |
          $issueAsJson = '${{ steps.parser.outputs.parsed-issue }}'
          $issue = ConvertFrom-Json $issueAsJson
          $issueAsJsonIndented = ConvertTo-Json $issue
          $expectedIssueAsJson = '{
            "nuget-id": "dotnet-sdk-extensions",
            "nuget-version": "1.0.13-alpha",
            "auto-generate-release-notes": "Yes",
            "auto-generate-release-notes-optional": "",
            "custom-release-notes": "## Custom release notes \n\nTest 123\n\nAnother line:\n- point 1\n- point 2\n- point 3",
            "operating-systems": {
              "macos": true,
              "windows": true,
              "linux": false,
              "i-dont-know": false
            }
          }'
          
          Write-Output $issueAsJsonIndented
          if($expectedIssueAsJson -eq $issueAsJsonIndented) {
            Write-Output "::notice::Action produced the expected output. See the output from the step 'Output and assert parsed issue'."
          }
          else {
            Write-Output "::error::Action didn't produce expected output. See the output from the step 'Output and assert parsed issue'."
          }

